### ISSUE TITLE
bgStrokeColor

### ISSUE THREAD

**Issue by Ahtisham-01** [alptugidin/react-circular-progress-bar#1]
bgStrokecolor is not working on  npm package

**Comment by alptugidin** [comment]
Can you provide a more detail? And, which browser are you using?

**Comment by iSultanz** [comment]
Same problem here
        "@alptugidin/react-circular-progress-bar": "1.1.0",
using on react nextjs v12
        <Flat
          progress={progress}
          text={'COMPLETION RATE'}
          showMiniCircle={false}
          sx={{
            strokeColor: '#22aae1',
            bgStrokeColor: '#e9e9e9',
            barWidth: 3,
            valueSize: 25,
            valueWeight: 'bold',
            valueColor: '#33343c',
            textSize: 6,
            textColor: '#8c8c8f',
            loadingTime: 900,
          }}
        />
       
      on chrome browser and the bg stroke color showing as transparent

**Comment by alptugidin** [comment]
fixed in v1.1.1
